//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capstone.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string backupdirectory1 {
            get {
                return ((string)(this["backupdirectory1"]));
            }
            set {
                this["backupdirectory1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string backupdirectory2 {
            get {
                return ((string)(this["backupdirectory2"]));
            }
            set {
                this["backupdirectory2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string backupdirectory3 {
            get {
                return ((string)(this["backupdirectory3"]));
            }
            set {
                this["backupdirectory3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string backupdirectory4 {
            get {
                return ((string)(this["backupdirectory4"]));
            }
            set {
                this["backupdirectory4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string backupdirectory5 {
            get {
                return ((string)(this["backupdirectory5"]));
            }
            set {
                this["backupdirectory5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool chkboxbackupdir3 {
            get {
                return ((bool)(this["chkboxbackupdir3"]));
            }
            set {
                this["chkboxbackupdir3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool chkboxbackupdir4 {
            get {
                return ((bool)(this["chkboxbackupdir4"]));
            }
            set {
                this["chkboxbackupdir4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool chkboxbackupdir5 {
            get {
                return ((bool)(this["chkboxbackupdir5"]));
            }
            set {
                this["chkboxbackupdir5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ad_dash_firstname {
            get {
                return ((string)(this["ad_dash_firstname"]));
            }
            set {
                this["ad_dash_firstname"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ad_dash_middlename {
            get {
                return ((string)(this["ad_dash_middlename"]));
            }
            set {
                this["ad_dash_middlename"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ad_dash_lastname {
            get {
                return ((string)(this["ad_dash_lastname"]));
            }
            set {
                this["ad_dash_lastname"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ad_dash_position {
            get {
                return ((string)(this["ad_dash_position"]));
            }
            set {
                this["ad_dash_position"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ad_dash_hierarchylvl {
            get {
                return ((string)(this["ad_dash_hierarchylvl"]));
            }
            set {
                this["ad_dash_hierarchylvl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string admin_backupdirectory1 {
            get {
                return ((string)(this["admin_backupdirectory1"]));
            }
            set {
                this["admin_backupdirectory1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string admin_backupdirectory2 {
            get {
                return ((string)(this["admin_backupdirectory2"]));
            }
            set {
                this["admin_backupdirectory2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string admin_backupdirectory3 {
            get {
                return ((string)(this["admin_backupdirectory3"]));
            }
            set {
                this["admin_backupdirectory3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string admin_backupdirectory4 {
            get {
                return ((string)(this["admin_backupdirectory4"]));
            }
            set {
                this["admin_backupdirectory4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string admin_backupdirectory5 {
            get {
                return ((string)(this["admin_backupdirectory5"]));
            }
            set {
                this["admin_backupdirectory5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool admin_chkboxbackupdir3 {
            get {
                return ((bool)(this["admin_chkboxbackupdir3"]));
            }
            set {
                this["admin_chkboxbackupdir3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool admin_chkboxbackupdir4 {
            get {
                return ((bool)(this["admin_chkboxbackupdir4"]));
            }
            set {
                this["admin_chkboxbackupdir4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool admin_chkboxbackupdir5 {
            get {
                return ((bool)(this["admin_chkboxbackupdir5"]));
            }
            set {
                this["admin_chkboxbackupdir5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ad_dash_emailad {
            get {
                return ((string)(this["ad_dash_emailad"]));
            }
            set {
                this["ad_dash_emailad"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string loginusername {
            get {
                return ((string)(this["loginusername"]));
            }
            set {
                this["loginusername"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string loginpassword {
            get {
                return ((string)(this["loginpassword"]));
            }
            set {
                this["loginpassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string staff_dash_firstname {
            get {
                return ((string)(this["staff_dash_firstname"]));
            }
            set {
                this["staff_dash_firstname"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string staff_dash_middlename {
            get {
                return ((string)(this["staff_dash_middlename"]));
            }
            set {
                this["staff_dash_middlename"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string staff_dash_lastname {
            get {
                return ((string)(this["staff_dash_lastname"]));
            }
            set {
                this["staff_dash_lastname"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string staff_dash_position {
            get {
                return ((string)(this["staff_dash_position"]));
            }
            set {
                this["staff_dash_position"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string staff_dash_hierarchylvl {
            get {
                return ((string)(this["staff_dash_hierarchylvl"]));
            }
            set {
                this["staff_dash_hierarchylvl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string staff_dash_emailad {
            get {
                return ((string)(this["staff_dash_emailad"]));
            }
            set {
                this["staff_dash_emailad"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string memberuid {
            get {
                return ((string)(this["memberuid"]));
            }
            set {
                this["memberuid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string memberfirstname {
            get {
                return ((string)(this["memberfirstname"]));
            }
            set {
                this["memberfirstname"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string memberlastname {
            get {
                return ((string)(this["memberlastname"]));
            }
            set {
                this["memberlastname"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string membermiddlename {
            get {
                return ((string)(this["membermiddlename"]));
            }
            set {
                this["membermiddlename"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string memberstart {
            get {
                return ((string)(this["memberstart"]));
            }
            set {
                this["memberstart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string memberend {
            get {
                return ((string)(this["memberend"]));
            }
            set {
                this["memberend"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string memberid {
            get {
                return ((string)(this["memberid"]));
            }
            set {
                this["memberid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string memberaddress {
            get {
                return ((string)(this["memberaddress"]));
            }
            set {
                this["memberaddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string memberorganization {
            get {
                return ((string)(this["memberorganization"]));
            }
            set {
                this["memberorganization"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string membercontactno {
            get {
                return ((string)(this["membercontactno"]));
            }
            set {
                this["membercontactno"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string memberemail {
            get {
                return ((string)(this["memberemail"]));
            }
            set {
                this["memberemail"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string membercatchinvaliddates {
            get {
                return ((string)(this["membercatchinvaliddates"]));
            }
            set {
                this["membercatchinvaliddates"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string bkinvbkauthor {
            get {
                return ((string)(this["bkinvbkauthor"]));
            }
            set {
                this["bkinvbkauthor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string bkinvbktitle {
            get {
                return ((string)(this["bkinvbktitle"]));
            }
            set {
                this["bkinvbktitle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string bkinvplaceofpub {
            get {
                return ((string)(this["bkinvplaceofpub"]));
            }
            set {
                this["bkinvplaceofpub"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string bkinvpublisher {
            get {
                return ((string)(this["bkinvpublisher"]));
            }
            set {
                this["bkinvpublisher"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string bkinvisbn {
            get {
                return ((string)(this["bkinvisbn"]));
            }
            set {
                this["bkinvisbn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string bkinvclassifno {
            get {
                return ((string)(this["bkinvclassifno"]));
            }
            set {
                this["bkinvclassifno"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string bkcopyright {
            get {
                return ((string)(this["bkcopyright"]));
            }
            set {
                this["bkcopyright"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double bkbookwidth {
            get {
                return ((double)(this["bkbookwidth"]));
            }
            set {
                this["bkbookwidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double bkbooklength {
            get {
                return ((double)(this["bkbooklength"]));
            }
            set {
                this["bkbooklength"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string bkaccessionno {
            get {
                return ((string)(this["bkaccessionno"]));
            }
            set {
                this["bkaccessionno"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string bkinvsource {
            get {
                return ((string)(this["bkinvsource"]));
            }
            set {
                this["bkinvsource"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string bkinvprice {
            get {
                return ((string)(this["bkinvprice"]));
            }
            set {
                this["bkinvprice"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string bkinvdateacq {
            get {
                return ((string)(this["bkinvdateacq"]));
            }
            set {
                this["bkinvdateacq"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string bkinvauthorno {
            get {
                return ((string)(this["bkinvauthorno"]));
            }
            set {
                this["bkinvauthorno"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string bkinvavailability {
            get {
                return ((string)(this["bkinvavailability"]));
            }
            set {
                this["bkinvavailability"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string bkinvincbibl {
            get {
                return ((string)(this["bkinvincbibl"]));
            }
            set {
                this["bkinvincbibl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int bkinvincgloss {
            get {
                return ((int)(this["bkinvincgloss"]));
            }
            set {
                this["bkinvincgloss"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string bkinvincindex {
            get {
                return ((string)(this["bkinvincindex"]));
            }
            set {
                this["bkinvincindex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int bkinvbookshelfno {
            get {
                return ((int)(this["bkinvbookshelfno"]));
            }
            set {
                this["bkinvbookshelfno"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int bkinvbookshelflvl {
            get {
                return ((int)(this["bkinvbookshelflvl"]));
            }
            set {
                this["bkinvbookshelflvl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string memberidimgpath {
            get {
                return ((string)(this["memberidimgpath"]));
            }
            set {
                this["memberidimgpath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string dashboardactivestatus {
            get {
                return ((string)(this["dashboardactivestatus"]));
            }
            set {
                this["dashboardactivestatus"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string membsuffix {
            get {
                return ((string)(this["membsuffix"]));
            }
            set {
                this["membsuffix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string membnotif {
            get {
                return ((string)(this["membnotif"]));
            }
            set {
                this["membnotif"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string membdateposted {
            get {
                return ((string)(this["membdateposted"]));
            }
            set {
                this["membdateposted"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string bkbr_bktitle {
            get {
                return ((string)(this["bkbr_bktitle"]));
            }
            set {
                this["bkbr_bktitle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string bkbr_accno {
            get {
                return ((string)(this["bkbr_accno"]));
            }
            set {
                this["bkbr_accno"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string bkbr_aut {
            get {
                return ((string)(this["bkbr_aut"]));
            }
            set {
                this["bkbr_aut"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string bkbr_uid {
            get {
                return ((string)(this["bkbr_uid"]));
            }
            set {
                this["bkbr_uid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string bkbr_staffname {
            get {
                return ((string)(this["bkbr_staffname"]));
            }
            set {
                this["bkbr_staffname"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string bkbr_username {
            get {
                return ((string)(this["bkbr_username"]));
            }
            set {
                this["bkbr_username"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string br_bkbr_id {
            get {
                return ((string)(this["br_bkbr_id"]));
            }
            set {
                this["br_bkbr_id"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string br_uid {
            get {
                return ((string)(this["br_uid"]));
            }
            set {
                this["br_uid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string br_bktitle {
            get {
                return ((string)(this["br_bktitle"]));
            }
            set {
                this["br_bktitle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string br_accno {
            get {
                return ((string)(this["br_accno"]));
            }
            set {
                this["br_accno"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string br_author {
            get {
                return ((string)(this["br_author"]));
            }
            set {
                this["br_author"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string br_dtbr {
            get {
                return ((string)(this["br_dtbr"]));
            }
            set {
                this["br_dtbr"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string br_duedt {
            get {
                return ((string)(this["br_duedt"]));
            }
            set {
                this["br_duedt"] = value;
            }
        }
    }
}
